### ISSUE TITLE
NPM global install fails on Mac

### ISSUE THREAD

**Issue by slavikshen** [bubenshchykov/ngrok#89] opened 2017-08-22 11:17 UTC
There is an error in the post installation.
BTW, yarn can install it.

sudo npm install -g ngrok/usr/local/bin/ngrok -> /usr/local/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.17 postinstall /usr/local/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ngrok/ngrok.zip'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.17 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@2.2.17 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bubenshchykov** [comment] 2017-08-22 11:43
thx @slavikshen , a possible duplicate of #88 
hopefully, we'll fix it soon with @gaoqiankun

**Comment by bubenshchykov** [comment] 2017-08-23 21:55
might be fixed in 2.2.19, @slavikshen can you try again?

**Closed** 2017-08-23 21:58 UTC
