### ISSUE TITLE
npm install fails on Windows 7 Pro

### ISSUE THREAD

**Issue by nkzawa** [bubenshchykov/ngrok#44] opened 2016-01-29 13:06 UTC
We got an issue report about the error. I'm not sure, but guess Windows is not supported?

Please see https://github.com/socketio/engine.io/issues/379

**Comment by bubenshchykov** [comment] 2016-01-30 01:50
ngrok should work for windows
postinstall script checks the current platform and fetches corresponding ngrok bins
I only saw it failing few times because bins hosting was temporary was not responsive 

@vicneanschi 
is it a permanent issue?
which os?  ```console.log(require('os').platform(), require('os').arch())```

**Comment by vicneanschi** [comment] 2016-01-30 04:53
It's permanent issue for me

> console.log(require('os').platform(), require('os').arch())
win32 x64
undefined
>

**Comment by bubenshchykov** [comment] 2016-01-30 17:23
@vicneanschi let's see if some Windows guy volunteers to debug it and fix, as unfortunately I have no time and will to install VM

meanwhile, try to install it with highest loglevel ```npm install -ddd``` and share the result
also, have you tried installing it via latest npm? ```npm install npm@3.6.0```

**Comment by jrios** [comment] 2016-02-08 20:18
Are you behind a firewall that is preventing https traffic? I'm running into a similar issue on my machine with both the mac and windows installers using npm. I think that the culprit might be the https.get call in the postinstall script.

here's my node versions: node v4.2.2 and npm v3.7.2. We have had this trouble before where I work where node scripts and post installs have problems getting traffic from over our firewall.

**Comment by vicneanschi** [comment] 2016-02-08 22:31
I've tested with npm@3.7.1
Here is the [npm log](https://gist.github.com/vicneanschi/803df58c3fe2f0523f36)

**Comment by bubenshchykov** [comment] 2016-02-09 04:02
@vicneanschi 
try to remove node_modules and cache ```npm cache clean```
also, try to install ngrok directly ```npm install ngrok``` - to localize the issue

**Comment by vicneanschi** [comment] 2016-02-09 04:05
that was actually a log of a direct install without node_modules.

**Comment by bubenshchykov** [comment] 2016-02-10 13:11
it should work. i was using it on 0.10.28 (osx), and there are integration tests for 
```
node_js:
  - "4.0.0"
  - "0.12"
  - "0.11"
```

i'll get windows machine in few hours and let you know

**Comment by bubenshchykov** [comment] 2016-02-10 15:45
tried windows, no luck reproducing an issue yet.
i just tried  ```npm cache clean && npm install ngrok``` on:
node: 0.10.33
npm: 3.7.1
platform: win32
arch: ia32 (you have x64, but I don't think it that matters here)

google an error from your log "Error: EPERM, rename .. node-uuid'" - some people say smart things about file descriptors or locks... for some node upgrade helped, if that's an option for you. https://github.com/Medium/phantomjs/issues/19 https://github.com/npm/npm/issues/9696

**Comment by bubenshchykov** [comment] 2016-03-12 14:32
can you try the latest ngrok 2.1.5 ? it has major fixes and different node_modules tree, so it might fix your  case too

**Comment by bubenshchykov** [comment] 2016-03-14 09:13
Assuming it's fixed in latest ngrok (2.1.6) and closing :)
Feel free to re-open in case of any problems.

**Closed by bubenshchykov** 2016-03-14 09:13 UTC
Labels: windows help needed
