### ISSUE TITLE
Post install script is failing (sometimes) for v0.1.x

### ISSUE THREAD

**Issue by cristiandouce** [bubenshchykov/ngrok#35] opened 2015-09-03 23:23 UTC
```
$ npm i
-
> ngrok@0.1.98 postinstall /Users/some/test/node_modules/zuul-ngrok/node_modules/ngrok
> node ./postinstall.js

ngrok - Downloading newest binary...
ngrok - Zipfile received (https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?os=darwin&arch=amd64&channel=stable) ...
[Error: Could not find the End of Central Directory Record]
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/some/.nvm/v0.12.7/bin/node" "/Users/some/.nvm/v0.12.7/bin/npm" "i"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ngrok@0.1.98 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@0.1.98 postinstall script 'node ./postinstall.js'.
npm ERR! This is most likely a problem with the ngrok package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ngrok
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/some/test/npm-debug.log
```

Notice the: `[Error: Could not find the End of Central Directory Record]`

**Comment by bubenshchykov** [comment] 2015-09-04 02:41
worked for me a minute ago, please try again - could be a random glitch on ngrok hosting

```
> node ./postinstall.js

ngrok - downloading newest binary...
ngrok - binary downloaded (https://dl.ngrok.com/ngrok_2.0.19_darwin_amd64.zip)...
ngrok - binary unpacked.
```

**Comment by cristiandouce** [comment] 2015-09-04 03:07
@bubenshchykov version?
Look at the log:
> ngrok@0.1.98 postinstall /Users/some/test/node_modules/zuul-ngrok/node_modules/ngrok

**Comment by bubenshchykov** [comment] 2015-09-05 15:16
@cristiandouce 
0.1.98 uses ngrok1 bins - the seems to be removed :( 
@inconshreveable are ngrok1 bins officially removed an no more supported?

**Comment by andrewwakeling** [comment] 2015-09-17 22:06
I'm currently hitting this issue with the api.equinox.io URL on 0.1.99.

**Comment by inconshreveable** [comment] 2015-09-17 22:08
The v1 bins are still available and haven't gone anywhere. They're all still supported. Do you have problems even if you try to download them directly: https://ngrok.com/download/1 (i've seen some networks where admins have taken to blocking everything about ngrok very explicitly)

**Comment by andrewwakeling** [comment] 2015-09-17 22:15
Thanks. It looks I might be experiencing some network issues on my end.

**Comment by bubenshchykov** [comment] 2015-09-18 13:49
@andrewwakeling could you please confirm that all is good? so we can maybe just close the issue :)

**Comment by cristiandouce** [comment] 2015-09-18 14:09
The issue is that sometimes the binaries for v1 from api.equinox.io are unreachable to download. Therefore the postinstall script fails.
That is independently from the network since I've tried it from my local machine and a CI in use-east and another in us-west :smile: 
Right now it works, but it like I said... it fails from time to time.

Is it possible to move those binaries to somewhere else?

**Comment by bubenshchykov** [comment] 2015-09-20 10:12
the binaries belong to @inconshreveable :)

**Comment by cristiandouce** [comment] 2015-09-20 16:58
:boom: yet, like I said, the api.equinox.io enpoint to the binaries times out from time to time.

**Comment by bubenshchykov** [comment] 2015-09-21 06:20
@cristiandouce I understand. I think I heard about 10 times about api.equinox.io instability. I checked the download urls and they are correct (compared to https://ngrok.com/download/1). I don't think @inconshreveable  wants to move old ngrok1 bins to other hosting, so what I can do is to make a fork "ngrok-old" and add some retry (let's say 5 imes) for postinstall fetch. 

Also "ngrok-old" could be a nice idea, because it works differently, uses old ngrok hosting and might be deprecated soon. But we'll be able to maintain both ngrok (v2) and ngrok-old (v1) simultaneously. 

let me know if it makes sense, and I'll push it quickly

**Comment by inconshreveable** [comment] 2015-09-21 07:26
I'd be okay moving ngrok older binaries to a different place since they're unlikely to change anymore. I've also resolved an issue that was causing download instability from equinox.io (and all of that infrastructure is getting updated soon as well)

**Comment by bubenshchykov** [comment] 2015-09-24 00:14
@cristiandouce when was the last time post-install failed for you?

**Comment by cristiandouce** [comment] 2015-09-24 04:05
@bubenshchykov week ago on my CI :cry:

**Comment by bubenshchykov** [comment] 2015-09-24 14:13
Let's close the ticket then as it might be already fixed. I would rather focus on ngrok 2 and make it good. Cheers!

**Comment by cristiandouce** [comment] 2015-09-24 16:38
:+1: +1 for ngrok 2 focus :smile:

**Comment by cristiandouce** [comment] 2015-09-24 16:38
Thanks for the assistance!

**Comment by refazul-refat** [comment] 2017-07-05 07:07
I think postinstall still fails one out of five times. This is what i had to do in a deploy script:

`npm install --save --ignore-scripts`
`curl -o ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip`
`unzip ngrok.zip`
`rm node_modules/ngrok/bin/ngrok`
`cp ngrok node_modules/ngrok/bin/ngrok`

**Comment by bubenshchykov** [comment] 2017-07-05 13:34
thanks for letting me know! that has something to do with equinox.io. I will add automatic retries to post-install script, let's see if it helps

**Comment by inconshreveable** [comment] 2017-07-06 23:59
we just fixed a race condition in the asset downloading code of equinox last night. it's very likely that this could have been the cause of the errors. just an fyi!

**Closed** 2017-07-07 09:17 UTC

**Comment by joshuaalpuerto** [comment] 2017-11-17 03:36
Hi all,

My build is failing because of this error.

<img width="886" alt="screen shot 2017-11-17 at 11 34 19 am" src="https://user-images.githubusercontent.com/7126484/32928113-5ecdecb0-cb8b-11e7-99b7-560540c6eab6.png">

When I tried to visit the link: [https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip](https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip) Im getting Application Error.

<img width="1183" alt="screen shot 2017-11-17 at 11 34 29 am" src="https://user-images.githubusercontent.com/7126484/32928130-7375cd9a-cb8b-11e7-9567-8b326acca03c.png">

Cheers!

**Comment by joshuaalpuerto** [comment] 2017-11-17 04:18
I was able to download the file now and my build is working again.

**Comment by bubenshchykov** [comment] 2017-11-17 07:39
Hi! Looks like a temporary equinox hosting issue. If that happens again,
you can host a needed ngrok binary yourself, and set NGROK_CDN_URL env var
before npm install. I will look into issue later today too, at least it
needs a better error message :)

**Comment by cimocimocimo** [comment] 2017-11-25 08:10
Happening again, looks like when the script tries to download this file:
https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?channel=stable&os=darwin&arch=amd64

it get's this error from equinox:
`{
  "errors": [
    {
      "message": "Requests to this resource require authentication. No authorization token was present in the request. You must send a valid authorization token in the Authorization header using the Bearer auth. Example: 'Authorization: Bearer {secret}'",
      "metadata": {
        "authorization-header": ""
      }
    }
  ]
}`

**Comment by bubenshchykov** [comment] 2017-11-25 14:30
hi @inconshreveable, pls help

**Comment by cimocimocimo** [comment] 2017-11-25 22:19
Just a thought, but could this be an issue with Equinox.io? Perhaps they are blocking access through this url:
https://api.equinox.io/1/Applications/ap_pJSFC5wQYkAyI0FIVwKYs9h1hW/Updates/Asset/ngrok.zip?channel=stable&os=darwin&arch=amd64

But it looks like this working url might fetch the same file but with a different format:
https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip

**Comment by bubenshchykov** [comment] 2017-11-25 22:22
@cimocimocimo I guess you are using an old module version
all bins are hosted on https://bin.equinox.io/..  https://github.com/bubenshchykov/ngrok/blob/master/postinstall.js#L8
Get the latest ngrok@2.2.24 and let me know :)

**Comment by cimocimocimo** [comment] 2017-11-26 00:54
Ok, I'm sorry. Seems I had two repos on my HD (long story). I was running yarn in one and changing the version numbers in the other directory. Got that straightened out and now everything is working perfectly. Thank you for for your time!
