### ISSUE TITLE
error: unhandled promise rejection Error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hgezim** [bubenshchykov/ngrok#100] opened 2017-12-19 20:45 UTC
I'm on Mac OS 10.12.6 (16G1036) with node v9.3.0 and npm 5.6.0 with ngrok 2.2.22.

I'm getting this error intermittently: 

Full trace:

```
error: unhandled promise rejection Error: panic: runtime error: invalid memory address or nil pointer dereference

github.com/inconshreveable/olive/recover.go:40
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
<autogenerated>:132
github.com/inconshreveable/olive/recover.go:29
runtime/asm_amd64.s:514
runtime/panic.go:489
github.com/inconshreveable/olive/error.go:37
runtime/asm_amd64.s:514
runtime/panic.go:489
runtime/panic.go:63
runtime/signal_unix.go:290
lib/tunnel/client/reconnecting.go:39
lib/tunnel/client/session.go:97
ngrok/tunnel_session.go:138
ngrok/web_api.go:97
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/error.go:41
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/recover.go:32
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:367
github.com/inconshreveable/olive/logger.go:17
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
<autogenerated>:30
github.com/go-martini/martini/router.go:373
github.com/go-martini/martini/router.go:250
github.com/go-martini/martini/router.go:120
ngrok/src/ngrok/web.go:27
runtime/asm_amd64.s:515
reflect/value.go:434
reflect/value.go:302
github.com/codegangsta/inject/inject.go:102
github.com/go-martini/martini/martini.go:173
github.com/go-martini/martini/martini.go:69

    at Request._callback (/project-path/node_modules/ngrok/index.js:177:10)
    at Request.self.callback (/project-path/node_modules/request/request.js:188:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/project-path/node_modules/request/request.js:1171:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/project-path/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1062:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by bubenshchykov** [comment] 2017-12-19 23:38
@inconshreveable do you recognize this error? can it be an old issue when we try to create tunnel when ngrok is not yet ready?

**Comment by inconshreveable** [comment] 2017-12-20 15:37
there is no version of ngrok 2.2.22. the latest version is 2.2.8?

**Comment by bubenshchykov** [comment] 2017-12-20 16:10
It’s a version of node module :) i believe the version of ngrok is latest

**Comment by hgezim** [comment] 2017-12-20 18:56
That's correct, I'm on ngrok 2.2.8 but the node module is at 2.2.22.

**Comment by bubenshchykov** [comment] 2017-12-22 09:02
@inconshreveable to remind how module works
- we start ngrok with "start --none --log=stdout"
- we wait for ngrok message "starting web service.*addr=(\d+\.\d+\.\d+\.\d+:\d+)" 
- we then immediately use internal ngrok api to create tunnels
- if ngrok returns status 500 with "... panic ..." or 502 with "tunnel session not ready yet", then we wait 200ms, and retry POSTing tunnel again (100 retries max)

As I see from the stack of @hgezim error, he gets all 100 retries (approximately 20 seconds), but POST tunnel still fails. Have you seen it before?

**Comment by jwickens** [comment] 2017-12-22 09:05
Maybe slightly different issue, but I solved this issue by installing request (rather than relying on the one one specified in dependencies). Going through the logs and the code the above error was expected however for some reason request-promise was somehow being loaded in my project, which throws errors on non 200 requests. Adding request to the package.json provided the correct request library so that ngrok node wrapper could listen for this above error.

**Comment by bubenshchykov** [comment] 2017-12-22 09:11
@jwickens wow that looks like a super-weird npm glitch :)
```
"dependencies": {
    "request": "^2.55.0",
``` 
- that should install https://github.com/request/request with no surprises

**Comment by jwickens** [comment] 2017-12-23 14:40
@bubenshchykov yeah i saw that you had request as a dependency. It might have to do with the fact that I'm using Yarn workspaces which is an experimental feature.

**Comment by bubenshchykov** [comment] 2018-01-02 22:13
@hgezim finally got time to help
I can't reproduce it yet, so can you help me with few questions
- do you create one or many tunnels per node process?
- do you get this error immediately, or after some time? (all the retries in total take around 20 sec)
- what tunnel are you trying to create? (tcp, http, custom subdomain)

**Comment by jwickens** [comment] 2018-01-04 16:56
Hey guys even though i was able to get it running with the workaround i mentioned above i was still getting request-promise printing errors whenever that expected 502/500 was thrown. I got fed up and rewrote the wrapper to use request-promise-native and classes and im no longer getting this error. 

Here's a gist: https://gist.github.com/jwickens/0a6dc0655f756d01d01f7057537b057b

I have some questions about the "uiUrl" and how the auth token gets passed. But that might be better for another issue.

**Comment by bubenshchykov** [comment] 2018-01-04 17:26
@jwickens great job, new code looks great  :)
I still don't see a clear connection between your request-related problem and issue reported originally.. were you at least getting the same error message?

**Comment by jwickens** [comment] 2018-01-04 19:20
I agree it unclear if its the same bug. If @hgezim could answer your questions that would help. The stack traces i was getting were exactly the same except it was being thrown from `request-promise-core` rather than ngrok.

**Comment by bubenshchykov** [comment] 2018-01-04 19:37
Great! Let’s wait for @hgezim. Meanwhile, feel free to submit your PR, as
its code looks cleaner and nicer - i’ll review it, run test suite (needs
hidden authtokens) and accept it then :)

**Comment by bubenshchykov** [comment] 2018-03-03 10:29
@hgezim @jwickens try ngrok 3.0.0 :)
closing this issue as major update has been pushed

**Closed by bubenshchykov** 2018-03-03 10:29 UTC
Labels: bug
