### ISSUE TITLE
Issue with Global Install of Ngrok in Linux With NPM

### ISSUE THREAD

**Issue by TKOBabu** [bubenshchykov/ngrok#87] opened 2017-07-22 19:37 UTC
### Issue that arises.
Done with Arch Linux using npm version 5.3.0 with Linux Kernel 4.11.5-1-ARCH
```
sudo npm i -g ngrok
/usr/bin/ngrok -> /usr/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.15 postinstall /usr/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/ngrok/ngrok.zip'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.15 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngrok@2.2.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-22T14_30_23_601Z-debug.log
```

Content from Log File about the error

```
2136 verbose lifecycle ngrok@2.2.15~postinstall: CWD: /usr/lib/node_modules/ngrok
2137 silly lifecycle ngrok@2.2.15~postinstall: Args: [ '-c', 'node ./postinstall.js' ]
2138 silly lifecycle ngrok@2.2.15~postinstall: Returned: code: 1  signal: null
2139 info lifecycle ngrok@2.2.15~postinstall: Failed to exec postinstall script
2140 verbose unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
2141 verbose stack Error: ngrok@2.2.15 postinstall: `node ./postinstall.js`
2141 verbose stack Exit status 1
2141 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
2141 verbose stack     at emitTwo (events.js:125:13)
2141 verbose stack     at EventEmitter.emit (events.js:213:7)
2141 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2141 verbose stack     at emitTwo (events.js:125:13)
2141 verbose stack     at ChildProcess.emit (events.js:213:7)
2141 verbose stack     at maybeClose (internal/child_process.js:897:16)
2141 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
2142 verbose pkgid ngrok@2.2.15
```

**Comment by bubenshchykov** [comment] 2017-07-22 22:19
thx for reporting!
it looks like it's a regression of previous pr
https://github.com/bubenshchykov/ngrok/pull/85/files#diff-551007241ae61889b0f85f47aa764343R106

@gaoqiankun ```var tempFile = path.join(os.tmpdir(), 'ngrok.zip'); var outputStream = fs.createWriteStream(tempFile);``` - do you see some permission problem and maybe a workaround here?

I can quickly add outputStream.on('error') handler to prevent uncaught, but I'm not sure what the problem is yet

**Comment by TKOBabu** [comment] 2017-07-22 22:37
Hi,

No problem. I am working on a project right now, but I should be done with it in 3-ish hours. If you want and have not solved it by then, I can take a look and see if I can resolve it and will add a pull request if I do.

**Comment by gaoqiankun** [comment] 2017-07-25 03:35
@TKOBabu 
I have tried `sudo npm i -g ngrok` on `archlinux`, but i got a lot package not found error
e.g.
```
vagrant@archlinux:~$ sudo npm i -g ngrok
/usr/bin/ngrok -> /usr/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.15 postinstall /usr/lib/node_modules/ngrok
> node ./postinstall.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'hawk'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/request/request.js:9:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! Linux 4.11.9-1-ARCH
```
```
vagrant@archlinux:~$ sudo npm i -g ngrok
/usr/bin/ngrok -> /usr/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.15 postinstall /usr/lib/node_modules/ngrok
> node ./postinstall.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'safe-buffer'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/request/lib/helpers.js:5:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm ERR! Linux 4.11.9-1-ARCH
```
But, ngrok does not depend on these packages.
Then, i install ngrok on ubuntu by `sudo npm i -g ngrok` and  on cygwin by`npm i -g ngrok`, it works fine.
```
gaoqiankun@dev1:/home/vagrant$ sudo npm i -g ngrok
/usr/bin/ngrok -> /usr/lib/node_modules/ngrok/bin/ngrok

> ngrok@2.2.15 postinstall /usr/lib/node_modules/ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
ngrok - downloading progress: 5363700/5363700
ngrok - binary downloaded to /usr/lib/node_modules/ngrok/bin/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1saW51eC1hbWQ2NC56aXA=.zip
ngrok - unpacking binary
ngrok - binary unpacked to /usr/lib/node_modules/ngrok/bin/ngrok
/usr/lib
└── ngrok@2.2.15
```
I don't think creating read/write stream will cause permission problem, and I never use archlinux before, can you give me some more time, to find what the real problem is.

**Comment by bubenshchykov** [comment] 2017-07-25 08:51
@gaoqiankun @TKOBabu thanks for investigation! 
I tried global install on mac only, with and without cached bin - both cases worked fine.
can you try to bump npm and install ngrok again ```npm i npm -g``` ?

**Comment by gaoqiankun** [comment] 2017-07-26 02:52
@bubenshchykov 
`sudo npm i -g npm` works successfuly, but when i run `npm --version`, it throw error
```
vagrant@archlinux:~$ sudo npm i -g npm@2
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
+ npm@2.15.12
added 69 packages, removed 278 packages and updated 133 packages in 40.023s
vagrant@archlinux:~$ npm -v
module.js:487
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:18:11
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:75:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
vagrant@archlinux:~$
```
Then i tried `sudo npm i -g typescript`, it works fine
```
vagrant@archlinux:~$ sudo npm i -g typescript
/usr/bin/tsc -> /usr/lib/node_modules/typescript/bin/tsc
/usr/bin/tsserver -> /usr/lib/node_modules/typescript/bin/tsserver
typescript@2.4.2 /usr/lib/node_modules/typescript
vagrant@archlinux:~$ ts
ts        tsc       tset      tsort     tsserver
vagrant@archlinux:~$ ts --help
Unknown option: help
usage: ts [-r] [-i | -s] [format]
vagrant@archlinux:~$ tsc --help
Version 2.4.2
Syntax:   tsc [options] [file ...]

Examples: tsc hello.ts
          tsc --outFile file.js file.ts
          tsc @args.txt
...
```
Then `sudo npm i -g node-sass`,  and i got *permission* error
```
vagrant@archlinux:~$ sudo npm i -g node-sass
/usr/bin/node-sass -> /usr/lib/node_modules/node-sass/bin/node-sass

> node-sass@4.5.3 install /usr/lib/node_modules/node-sass
> node scripts/install.js

fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/lib/node_modules/node-sass/package.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.Module._extensions..json (module.js:586:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/node-sass/lib/extensions.js:7:9)
    at Module._compile (module.js:569:30)
npm ERR! Linux 4.11.9-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "node-sass"
npm ERR! node v8.2.1
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/npm-debug.log
```
So, it may be a bug of npm on archlinux.

**Comment by bubenshchykov** [comment] 2017-07-26 09:00
please try ``` sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}``` as npm suggests https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by bubenshchykov** [comment] 2017-08-23 21:57
@TKOBabu might be fixed in latest version, can you try?
if issue still happens, pls report in #88 - there was a discussion there

**Closed by bubenshchykov** 2017-08-23 21:57 UTC

**Comment by ankibalyan** [comment] 2018-03-08 12:41
@bubenshchykov should not modify `bin,share`, It may get worse. I've experianced.
`sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

just `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules}` should work.

**Comment by malivp3494** [comment] 2018-05-23 10:18
Anyone who's going to use 

> sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

think 100 times before. I just had to reinstall entire ubuntu cause I accidently ran 

> chown -R 

on /usr . There's no solution if you change permissions of files that you don't even know.

**Comment by ankibalyan** [comment] 2018-05-23 13:39
@malivp3494 I've already mentioned that above. You should have read that. :smiling_imp:

**Comment by malivp3494** [comment] 2018-05-24 03:41
@ankibalyan  yeah, but I read the solution somewhere else, and went with it. And now I regret it. There really needs to be other way around instead using ```chown -R```

**Comment by ankibalyan** [comment] 2018-05-24 07:00
way I do is, 
Download node, npm binaries seperatly than put the excutable file path in env var $PATH rather than installing os dependents. It waorks way smothly and no need of sudo anymore.

**Comment by malivp3494** [comment] 2018-05-24 09:36
@ankibalyan You should comment with a short procedure here, if you have time. For future users, who are going to use this, it will help a lot.

**Comment by bubenshchykov** [comment] 2018-05-24 15:08
hi guys, sorry to cause you problems by suggesting sudo in the comment above. i knew sudo is risky, but didn't know it could kill an entire OS :(

```npm i ngrok -g``` should just work itself. it works fine on OSX, but I see that it fails on linux
I'll take a closer look at permissions problem, might be possible to adjust postinstall.js

**Comment by ankibalyan** [comment] 2018-05-24 18:56
or one can follow, these steps https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by OZZlE** [comment] 2019-01-17 08:41
I was doing `sudo npm install -g ngrok --unsafe-perm=true --allow-root` inside my vagrant box, I just removed `sudo` and it worked fine :)

**Comment by amandeepmittal** [comment] 2019-03-10 18:59
@OZZlE your solution worked! Thank you so much. Though I filed an issue her #140.

**Comment by Farhan-Haseeb** [comment] 2019-10-23 10:28
> hi guys, sorry to cause you problems by suggesting sudo in the comment above. i knew sudo is risky, but didn't know it could kill an entire OS :(
> 
> `npm i ngrok -g` should just work itself. it works fine on OSX, but I see that it fails on linux
> I'll take a closer look at permissions problem, might be possible to adjust postinstall.js

I was facing the same problem in OSX even `sudo`didn't work. I had to use `sudo npm install -g ngrok --unsafe-perm=true --allow-root`

**Comment by viatanas** [comment] 2023-01-03 12:35
> > hi guys, sorry to cause you problems by suggesting sudo in the comment above. i knew sudo is risky, but didn't know it could kill an entire OS :(
> > `npm i ngrok -g` should just work itself. it works fine on OSX, but I see that it fails on linux
> > I'll take a closer look at permissions problem, might be possible to adjust postinstall.js
> 
> I was facing the same problem in OSX even `sudo`didn't work. I had to use `sudo npm install -g ngrok --unsafe-perm=true --allow-root`

This is what worked for me - thanks!
