### ISSUE TITLE
ngrok fails to start in Windows 10 Bash

### ISSUE THREAD

**Issue by Carpetfizz** [bubenshchykov/ngrok#60] opened 2016-08-15 20:21 UTC
Hi,

I'm trying to use ngrok in Windows 10 Bash and I'm running into an issue. Nothing happens when I type in ngrok. Same thing occurs when I use the ngrok build from the official website.

Thanks for any information.

**Comment by bubenshchykov** [comment] 2016-08-16 01:38
Hi, thanks for reporting! I think it's a duplicate of https://github.com/bubenshchykov/ngrok/issues/58 - could you please share few details there

**Closed by bubenshchykov** 2016-08-16 01:38 UTC

**Comment by AlexHankins** [comment] 2019-11-08 19:13
Use `winpty ngrok` instead of just `ngrok`.  Works for me.
