### ISSUE TITLE
Nodemon restart: causes 103 error 

### ISSUE THREAD

**Issue by RongxinZhang** [bubenshchykov/ngrok#213] opened 2021-03-11 02:02 UTC
Hi,

### Context:
I'm currently using Ngrok within my express app.
I run my app using `nodemon  --ignore './profiles/' --exec ./bin/www`

In my main app file, I have routes and Ngrok:

```js
// Start ngrok
(async function () {
  try {
    const url = await ngrok.connect({
      authtoken: process.env.NGROK_AUTH_TOKEN,
      subdomain: "corcus",
      addr: "localhost:3030",
    });
    console.log("ngrok:", url);
  } catch (error) {
    console.log("ERROR: Ngrok", error);
  }
})();
```

### Problem:
Every time I make an edit to the page, nodemon restarts the app.
I then get the following error:

```js
ERROR: Ngrok { error_code: 103,
  status_code: 502,
  msg: 'failed to start tunnel',
  details: { err: 'remote gone away' } }
```

I've googled around and looked the current issues and found this: https://gist.github.com/spalladino/45a6e54d7942ac0bad64dd54d7d12467

However, nothing really solves my problem yet. Would love to get some advice or suggestion.

**Comment by philnash** [comment] 2021-03-22 12:11
I don't think that running ngrok from within a nodemon controller process is a good idea, since nodemon will restart the process which will kill the ngrok tunnels.

I'd recommend building a script to run nodemon and ngrok together, so that ngrok can stay live while nodemon restarts the process, as I wrote up in [this blog post here](https://philna.sh/blog/2021/03/15/restart-app-not-tunnel-ngrok-nodemon/) with a script based on the gist you linked.

Let me know if that helps at all.

**Comment by philnash** [comment] 2021-03-30 11:49
Hey, I'm going to close this as it's been quiet for a week and I believe my previous comment should help. If you are still having trouble, please re-open and let me know.

**Closed by philnash** 2021-03-30 11:49 UTC

**Comment by dheerajaggarwal** [comment] 2022-12-30 06:47
Although the issue is closed. But I was able to resolve the exact same issue by stopping my earlier active session on ngrok dashboard. I stopped all sessions on my terminal but somehow it was active. Just visit the below link to stop the session:
https://dashboard.ngrok.com/tunnels/agents
